apiVersion: v2
name: wildfly
description: Build and Deploy WildFly applications on OpenShift
type: "application"
version: 1.4.0

# This is the version number of the application being deployed.
# This maps to the WildFly S2I Images tag that is used for S2I build.
appVersion: "24.0"

maintainers:
  - email: wildfly-dev@lists.jboss.org
    name: WildFly
    url: https://wildfly.org
icon: https://design.jboss.org/wildfly/logo/final/wildfly_logomark_256px.png

dependencies:
- name: wildfly-common
  version: 1.3.0
  repository: file://../wildfly-common
